alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

features:
  - buildpack-stack=ubuntu-22

ingress:
  rules:
    - component:
        name: livewell-api
      match:
        path:
          prefix: /
      cors:
        allow_origins:
          - exact: https://jellyfish-app-7zc9e.ondigitalocean.app
            regex: ^(https?:\/\/)?([a-zA-Z0-9-]+\.)+ondigitalocean\.app\/?$
        allow_methods: ["GET", "POST"]
        allow_headers: ["Authorization"]
        expose_headers: ["Authorization"]
        max_age: 5h30m
        allow_credentials: true

name: lionfish-app
region: lon

services:
  - name: livewell-api
    github:
      branch: main
      repo: jones-agyemang/livewell-api
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    run_command: ./bin/rails s -p 8080
    source_dir: /
    envs:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        value: {{ $RAILS_MASTER_KEY }}
