alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: livewell-api
      match:
        path:
          prefix: /
    - component:
        name: livewell-api-2
      match:
        path:
          prefix: /livewell-api-2      
name: lionfish-app
region: lon
services:
  - dockerfile_path: Dockerfile
    github:
      branch: main
      repo: jones-agyemang/livewell-api
    http_port: 80
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    name: livewell-api-2
    source_dir: /
    envs:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        value: {{ $RAILS_MASTER_KEY }}
  - environment_slug: ruby-on-rails
    github:
      branch: main
      deploy_on_push: true
      repo: jones-agyemang/livewell-api
    http_port: 8080 # Matches the Rails server command
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    name: livewell-api
    run_command: rails server -p $PORT -e ${RAILS_ENV:-production}
    source_dir: /
    envs:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        value: {{ $RAILS_MASTER_KEY }}
