name: Deploy Rails API Application

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: livewell-api-db-prod
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2

    - name: Cache Bundler gems
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-bundler-

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --path vendor/bundle

    - name: Install PostgreSQL client
      run: sudo apt-get update && sudo apt-get install -y postgresql-client
  
    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h 127.0.0.1 -p 5432 -U postgres; do
          echo "Waiting for PostgreSQL..."
          sleep 1
        done

    - name: Run database migrations
      env:
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      run: |
        RAILS_ENV=production bundle exec rake db:migrate

    - name: Deploy the app
      uses: digitalocean/app_action/deploy@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        app_spec_location: .do/app.yaml  
