name: Deploy Rails API

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Setup Ruby
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1 # Update to your Ruby version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    # Step 4: Setup database (if necessary)
    - name: Setup database
      run: |
        RAILS_ENV=production bundle exec rake db:migrate

    # Step 5: Deploy the app using DigitalOcean
    - name: Deploy the app
      uses: digitalocean/app_action/deploy@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        app_spec_location: .do/app.yaml
