name: Deploy Rails API Application

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Setup Ruby
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2 # Update to your Ruby version

    # Step 3: Cache Bundler gems
    - name: Cache Bundler gems
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-bundler-

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --path vendor/bundle

    # Step 5: Debug - Print RAILS_MASTER_KEY
    - name: Print RAILS_MASTER_KEY
      env:
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      run: |
        echo "RAILS_MASTER_KEY: $RAILS_MASTER_KEY"

    # Step 6: Setup database
    - name: Setup database
      env:
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      run: |
        RAILS_ENV=production bundle exec rake db:migrate

    # Step 7: Deploy the app using DigitalOcean
    - name: Deploy the app
      uses: digitalocean/app_action/deploy@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        app_spec_location: .do/app.yaml
